-- Normalize the HTML generated by CNX before Pandoc writes MyST Markdown.
-- This filter intentionally keeps source anchors so converted cross-references
-- continue to land on the relevant exercise, example, or figure.

local function label_block(label)
  return pandoc.Para({ pandoc.Strong({ pandoc.Str(label) }) })
end

local function callout(div, label, class_name)
  table.insert(div.content, 1, label_block(label))
  div.classes = { class_name }
  div.attributes = {}
  return div
end

function Div(div)
  local kind = div.attributes['data-type'] or ''

  if kind == 'document-title' or kind == 'abstract' or kind == 'title' then
    return {}
  end

  if kind == 'page' or kind == 'section' or kind == 'figure-wrapper' or kind == 'media' then
    return div.content
  end

  if kind == 'exercise' then return callout(div, 'Practice', 'exercise') end
  if kind == 'problem' then return callout(div, 'Question', 'problem') end
  if kind == 'solution' then return callout(div, 'Solution', 'solution') end
  if kind == 'example' then return callout(div, 'Example', 'example') end
  if kind == 'note' then return callout(div, 'Note', 'note') end

  div.attributes = {}
  return div
end

function Header(header)
  -- CNX reserves levels 1 and 2 for the collection and module title. Each
  -- module becomes its own MyST page, so source h3/h4 headings shift to h2/h3.
  if header.level > 1 then header.level = header.level - 1 end
  header.attributes = {}
  header.classes = {}
  return header
end

function Span(span)
  if span.attributes['media-type'] == 'application/postscript' then return {} end
  if span.attributes['data-type'] == 'term' then return pandoc.Emph(span.content) end
  return span.content
end

function Link(link)
  link.attributes = {}
  link.classes = {}
  return link
end

function Image(image)
  image.identifier = ''
  image.attributes = {}
  image.classes = {}
  if #image.caption == 0 then
    image.caption = { pandoc.Str('Music notation example') }
  end
  return image
end
